# Generated by Django 4.2 on 2023-04-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('album_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('date_uploaded', models.DateTimeField(blank=True)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('art', models.ImageField(upload_to='static/image')),
                ('audio', models.FileField(upload_to='media/audio')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicbase.album')),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('art', models.ImageField(upload_to='static/images')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicbase.music')),
            ],
        ),
    ]
