# Generated by Django 4.1 on 2023-04-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
        migrations.AddField(
            model_name='album',
            name='album_art',
            field=models.FileField(null=True, upload_to='ststic/images'),
        ),
    ]
