# Generated by Django 4.1 on 2023-04-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbase', '0002_remove_album_album_logo_album_album_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.FileField(null=True, upload_to='static/images'),
        ),
    ]
